---
title: "Gov 50 Final Project"
author: "Alicia Campbell"
description: "Measuring the Relationship between Party Religiousity and Female Membership in Lebanon"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts (Milestone One)

I am interested in using the data set "Party Variation in Religiosity and Womens Leadership, Lebanon Dataset" to measure the relationship between party religiosity and share of women in party membership (perc) in Lebanon. Based on the results, I will examine the extent that party religiosity is associated with female membership, or lack thereof.


## Project Proposal (Milestone Two)

Research Question: Does party religiosity impact female party membership in Lebanon? 

Drawing on the “Party Variation in Religiosity and Women's Leadership, Lebanon Dataset," I aim to examine the extent to which religiosity of key political parties in Lebanon impacts the share of female membership in said party. I hypothesize that the share of female membership decreases as party religiosity increases. As is typical, I expect more religious parties to take more conservative stances with regards to the role of women in the political realm, which is often associated with an adherence to gender roles wherein women are seen as better suited to carry out more domestic-oriented than public-facing tasks. Conversely, I hypothesize that less religious parties in Lebanon will exhibit higher shares of female membership, given the more liberal and open ideology often associated with non-religious groups. My sample includes responses regarding religion and female membership from 18 different political parties in Lebanon of different levels of religiosity. My explanatory variable is level of party religiosity, with possible answers ranging from “Areligious and Secular” (coded as 5) to “Extremely Religious” (coded as 1).Tthe full ranking of choices are as follows: 1) Extremely Religious, 2) Conservative but not extremist religiosity 3) tolerant religiosity 4) confessional but civil secularism 5) A religious and Secular. My outcome variable is the share of female members in a given political party, represented as a percent.  For example, if the share of a female membership is 15, it would indicate that 15% of party members are female. According to the dataset summary, this data was collected “in person and via one-on-one interviews with party administrators, officials, and elites.” If I were to observe lower shares of female party membership for parties that are coded as having high levels of religiosity (likely coded as a 1 or 2), this would support my hypothesis. Conversely, if I were to observe the opposite effect, that female membership is higher for parties that exhibit higher levels of religiosity, this would provide evidence against my hypothesis. 


